
version: '3.3'

services:
  __PROJECT_NAME__:
    image: ghost:4
    restart: always
    ports:
      - 8080:2368
    volumes:
      - ~/__PROJECT_NAME__/data/content:/var/lib/ghost/content
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: database
      database__connection__user: root
      database__connection__password: __MYSQL_ROOT_PASSWORD__
      database__connection__database: ghost
      url: https://__DOMAIN__
      NODE_ENV: production

  database:
    image: mysql:8.0
    restart: always
    volumes:
      - ~/__PROJECT_NAME__/data/db:/var/lib/mysql
    ports:
      - "13928:3306"
    environment:
      MYSQL_ROOT_PASSWORD: __MYSQL_ROOT_PASSWORD__
      MYSQL_DATABASE: ghost
      MYSQL_USER: user
      MYSQL_PASSWORD: __MYSQL_USER_PASSWORD__
